### ISSUE TITLE
Error in Expansion Spans

### ISSUE THREAD

**Issue by margaretha** [KorAP/Krill#121]
```
[tt/p="NN"] []* [tt/p="NN"]
```
returns the following error message 
```
Caused by: java.lang.StackOverflowError
        at de.ids_mannheim.korap.query.spans.CandidateSpan.<init>(CandidateSpan.java:108) ~[Kustvakt-full-0.73-SNAPSHOT.jar:?]
        at de.ids_mannheim.korap.query.spans.ExpandedSpans.setCandidateList(ExpandedSpans.java:128) ~[Kustvakt-full-0.73-SNAPSHOT.jar:?]
```

**Comment by Akron** [comment]
That's very interesting.
