### ISSUE TITLE
SpanOr-Bug in spanWithin

### ISSUE THREAD

**Issue by Akron** [KorAP/Krill#3]
There is a bug in spanWithin that seems to be close to TestWithinIndex.queryJSONpoly2.

Breaking test in TestWithinIndex.queryJSONcomplexSpanOrTerm (span-or-bug branch).

Stacktrace:
```
          at org.apache.lucene.search.spans.SpanOrQuery$1.doc(SpanOrQuery.java:234)
          at de.ids_mannheim.korap.query.spans.WithinSpans.toSameDoc(WithinSpans.java:423)
          at de.ids_mannheim.korap.query.spans.WithinSpans.next(WithinSpans.java:375)
          at de.ids_mannheim.korap.KrillIndex.search(KrillIndex.java:1293)
          at de.ids_mannheim.korap.Krill.apply(Krill.java:304)
```

**Comment by Akron** [comment]
Fixed in 0.55.4.
